# Generated by Django 5.1.1 on 2024-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0002_menuitem_remove_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
