# Generated by Django 5.1.1 on 2024-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_project', '0003_ingredient_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('lbs', 'Pound'), ('oz', 'Ounce'), ('cups', 'Cup'), ('tsp', 'Teaspoon'), ('grm', 'Gram')], default='grm', max_length=4),
        ),
    ]
